CREATE DATABASE DuAn1
GO
USE DuAn1
GO

IF OBJECT_ID('MauSac') IS NOT NULL
DROP TABLE MauSac
GO
CREATE TABLE MauSac
(
MaMauSac UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenMauSac NVARCHAR(30),
)

IF OBJECT_ID('KichThuoc') IS NOT NULL
DROP TABLE KichThuoc
GO
CREATE TABLE KichThuoc
(
MaKichThuoc UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenKichThuoc NVARCHAR(30),
)

IF OBJECT_ID('LoaiSanPham') IS NOT NULL
DROP TABLE LoaiSanPham
GO
CREATE TABLE LoaiSanPham
(
MaLoaiSanPham UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenLoaiSanPham NVARCHAR(30),

)

IF OBJECT_ID('ChatLieu') IS NOT NULL
DROP TABLE ChatLieu
GO
CREATE TABLE ChatLieu
(
MaChatLieu UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenChatLieu NVARCHAR(30),
)

IF OBJECT_ID('SanPham') IS NOT NULL
DROP TABLE SanPham
GO
CREATE TABLE SanPham
(
MaSanPham INT IDENTITY(6,1) PRIMARY KEY,
TenSanPham NVARCHAR(30),
MaChatLieu UNIQUEIDENTIFIER,
MaLoaiSanPham  UNIQUEIDENTIFIER,
MaKichThuoc UNIQUEIDENTIFIER,
MaMauSac  UNIQUEIDENTIFIER,
SoLuong INT,
GiaBan FLOAT,
Mota NVARCHAR(100),
FOREIGN KEY (MaChatLieu) REFERENCES ChatLieu(MaChatLieu),
FOREIGN KEY (MaMauSac) REFERENCES MauSac(MaMauSac),
FOREIGN KEY (MaKichThuoc) REFERENCES KichThuoc(MaKichThuoc),
FOREIGN KEY (MaLoaiSanPham) REFERENCES LoaiSanPham(MaLoaiSanPham),
)

IF OBJECT_ID('KhuyenMai') IS NOT NULL
DROP TABLE KhuyenMai
GO
CREATE TABLE KhuyenMai
(
MaKhuyenMai INT IDENTITY(5,1) PRIMARY KEY NOT NULL,
TenKhuyenMai NVARCHAR(30),
NgayBatDau DATE,
NgayKetThuc DATE,
GiamGia INT,
TrangThai BIT,
MaSanPham INT,
FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham),
)

IF OBJECT_ID('NhanVien') IS NOT NULL
DROP TABLE NhanVien
GO 
CREATE TABLE NhanVien
(
MaNhanVien VARCHAR(10) PRIMARY KEY NOT NULL,
TenNhanVien NVARCHAR(30),
GioiTinh BIT,
NgaySinh DATE,
SoDienThoai VARCHAR(12),
Email VARCHAR(50),
MatKhau VARCHAR(30),
VaiTro NVARCHAR(50),
TrangThai NVARCHAR(50),
)

IF OBJECT_ID('KhachHang') IS NOT NULL
DROP TABLE KhachHang
GO
CREATE TABLE KhachHang
(
MaKhachHang INT IDENTITY(3,1) PRIMARY KEY NOT NULL,
TenKhachHang NVARCHAR(30),
SoDienThoai VARCHAR(12),
DiaChi NVARCHAR(100),
)

IF OBJECT_ID('HoaDon') IS NOT NULL
DROP TABLE HoaDon
GO
CREATE TABLE HoaDon
(
MaHoaDon INT IDENTITY(4,1) PRIMARY KEY NOT NULL,
MaNhanVien VARCHAR(10),
MaKhachHang INT,
NgayTao DATE,
TienShip FLOAT,
TongTien FLOAT,
HTThanhToan NVARCHAR(50),
TinhTrang NVARCHAR(50),
GhiChu NVARCHAR(100),
FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien),
FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
)

IF OBJECT_ID('ChiTietHoaDon') IS NOT NULL
DROP TABLE ChiTietHoaDon
GO
CREATE TABLE ChiTietHoaDon
(
MaHoaDon INT,
MaSanPham INT,
SoLuong INT,
DonGia FLOAT,
GiamGia INT,
ThanhTien FLOAT,
PRIMARY KEY(MaHoaDon,MaSanPham),
FOREIGN KEY(MaHoaDon) REFERENCES HoaDon(MaHoaDon),
FOREIGN KEY(MaSanPham) REFERENCES SanPham(MaSanPham),
)


INSERT INTO LoaiSanPham(TenLoaiSanPham) VALUES ('AO');
SELECT TenLoaiSanPham FROM;
	INSERT INTO ChatLieu(TenChatLieu) VALUES ('Cottong');
	INSERT INTO KichThuoc(TenKichThuoc) VALUES ('L');
	select * from KichThuoc